image: maven:latest
  
stages:
  - build
  - test
  - deploy
  
  cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - content/target
  policy: pull-push
  
  
before_script:
    - cd content
  
build-dev:
    stage: build
    cache:
        <<: *global_cache
        policy: push
    script:
        - mvn clean install -DskipTests
   
  
test-dev:
    stage: test
    cache:
        <<: *global_cache
        policy: pull
    script:
        - mvn test
  
deploy-dev:
  stage: deploy
  only:
        - dev
  script:
    - mvn azure-webapp:deploy
#   dependencies: 
#     - build-dev
