image: maven:latest
  
stages:
  - build
  - test
  - deploy
  
  
before_script:
    - cd content
  
build-dev:
    stage: build
    script:
        - mvn clean install -DskipTests
    cache:
        paths:
            - target/
    # artifacts:
    #     paths:
    #         - binaries/
  
test-dev:
    stage: test
    cache:
        paths:
            - target/
    # dependencies: 
    #     - build-dev
    script:
        - mvn test
  
deploy-dev:
  stage: deploy
  only:
        - dev
  script:
    - mvn azure-webapp:deploy
#   dependencies: 
#     - build-dev
