image: maven:latest
# image: maven:3-jdk-12-alpine
  
stages:
  - build
  - test
  - deploy
  
# variables:
#     MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    
# cache:
#     paths:
#         - ./.m2/repository/
  
  
before_script:
    - cd content
  
build-dev:
    stage: build
    script:
        - mvn clean install -DskipTests
    artifacts:
        paths:
            - content/target/
   
  
test-dev:
    stage: test
    script:
        - mvn test
    dependencies: 
        - build-dev
  
deploy-dev:
  stage: deploy
  only:
        - dev
  script:
    - mvn azure-webapp:deploy
#   dependencies: 
#     - build-dev
