image: maven:latest
  
stages:
  - build
  - test
  - deploy
  
  
before_script:
    - cd content
  
build-dev:
    stage: build
    script:
        - mvn clean install -DskipTests
    artifacts:
        paths:
            - content/target/*.jar
    # artifacts:
    #     paths:
    #         - binaries/
  
test-dev:
    stage: test
    artifacts:
        paths:
            - content/target/

    # artifacts:
    #     when: always
    #     reports:
    #     junit:
    #         - target/surefire-reports/TEST-*.xml
    # dependencies: 
    #     - build-dev
    script:
        - mvn test
  
deploy-dev:
  stage: deploy
  only:
        - dev
  script:
    - mvn azure-webapp:deploy
#   dependencies: 
#     - build-dev
