image: docker/compose:latest

services:
  - docker:dind
  
stages:
  - test
  - deploy
  
test:
    stage: test
    only:
        - production
    script:
        - echo run tests

before_script:
  - docker version
  - docker-compose version
  
step-deploy-prod:
  stage: deploy
  script:
    - cd content
    - docker-compose up -d --build
    # - docker-compose build
    # - docker-compose up
  only:
    - production
