image: maven:latest
  
stages:
  - build
  - test
  - deploy
  
cache:
  paths:
    - target/
  
before_script:
    - cd content
  
build-dev:
    stage: build
    script:
        - mvn clean install -DskipTests
  
test-dev:
    stage: test
    script:
        - mvn test
  
deploy-dev:
  stage: deploy
  only:
        - dev
  script:
    - mvn azure-webapp:deploy
