version: '3'

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    container_name: "mysql_db"
    environment:
      MYSQL_DATABASE: user_info
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '3308:3306'
    expose:
      - '3306'
    volumes:
      - my_db:/var/lib/mysql
    networks:
      - def

  app:
    container_name: app
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - def
    depends_on:
      - mysql_db
    links:
      - mysql_db


networks:
  def:
    driver: bridge

volumes:
  my_db:
